INSERT INTO profesores VALUES(1,'José Antonio','Aguilar Curado','-');
INSERT INTO profesores VALUES(2,'Míriam','Alcantarilla Rodríguez','-');
INSERT INTO profesores VALUES(3,'Luis','Angulo Jiménez','2º AFI');
INSERT INTO profesores VALUES(4,'Manuel','Arroyo Jaraba','2º CGA');
INSERT INTO profesores VALUES(5,'Alberto','Ávila Morales','1º BACH A');
INSERT INTO profesores VALUES(6,'Andrés','Bello Cañete','-');
INSERT INTO profesores VALUES(7,'Ana María','Cañero López','-');
INSERT INTO profesores VALUES(8,'Daniel','Carmona Gómez','-');
INSERT INTO profesores VALUES(9,'Juan','Carmona Luque','-');
INSERT INTO profesores VALUES(10,'Carmen María','Carrasco Fernández','-');
INSERT INTO profesores VALUES(11,'Teresa María','Carvajal Báez','-');
INSERT INTO profesores VALUES(12,'Fernando','Castilla Serrano','-');
INSERT INTO profesores VALUES(13,'Beatriz','Contreras Arroyo','-');
INSERT INTO profesores VALUES(14,'Mateo Jesús','Cruz Muñoz','-');
INSERT INTO profesores VALUES(15,'Tomás M.','Daza Utrero','-');
INSERT INTO profesores VALUES(16,'Amparo','De la Rosa Alabanda','2º BACH B');
INSERT INTO profesores VALUES(17,'Aurelia','Díaz Ramírez','1º CGA A');
INSERT INTO profesores VALUES(18,'Rafaela','Domínguez Muñoz','-');
INSERT INTO profesores VALUES(19,'Juan Enrique','Farfán Espuny','1º DAW');
INSERT INTO profesores VALUES(20,'Felipe José','Fernández Garrido','2º FPB');
INSERT INTO profesores VALUES(21,'Julián','Fernández González','2º BACH A');
INSERT INTO profesores VALUES(22,'José Manuel','Fernández Raboso','-');
INSERT INTO profesores VALUES(23,'María Inmaculada','García Barrera','-');
INSERT INTO profesores VALUES(24,'Fátima','Gómez Vega','-');
INSERT INTO profesores VALUES(25,'Feliciana','González Chico','-');
INSERT INTO profesores VALUES(26,'Cristina','González Del Tell','-');
INSERT INTO profesores VALUES(27,'María Eugenia','González Matito','-');
INSERT INTO profesores VALUES(28,'Juan Antonio','González Romano','CAGM');
INSERT INTO profesores VALUES(29,'Rocío','Jiménez Arce','-');
INSERT INTO profesores VALUES(30,'Alfonso','Jiménez Vílchez','1º ASIR');
INSERT INTO profesores VALUES(31,'Juan Bosco','Lara García','-');
INSERT INTO profesores VALUES(32,'Juan Antonio','Lara Medina','1º BACH B');
INSERT INTO profesores VALUES(33,'Elisa María','Linero Marín','-');
INSERT INTO profesores VALUES(34,'Mercedes','Macías Trejo','-');
INSERT INTO profesores VALUES(35,'Ana Belén','Marín García','-');
INSERT INTO profesores VALUES(36,'Francisco Eduardo','Martín Martín','2º DAW');
INSERT INTO profesores VALUES(37,'María Fernanda','Martínez Postigo','-');
INSERT INTO profesores VALUES(38,'Francisco','Martínez Vijuesca','-');
INSERT INTO profesores VALUES(39,'Ángela María','Martínez Villegas','-');
INSERT INTO profesores VALUES(40,'Ana','Matas Garrido','2º ESO C');
INSERT INTO profesores VALUES(41,'Rosendo','Matías Romero','-');
INSERT INTO profesores VALUES(42,'Aroa','Meana López','-');
INSERT INTO profesores VALUES(43,'Ana','Mediavilla Molina','-');
INSERT INTO profesores VALUES(44,'Amador','Mohedano Domínguez','3º ESO C');
INSERT INTO profesores VALUES(45,'Susana','Muñoz Fontanilla','-');
INSERT INTO profesores VALUES(46,'José Antonio','Muñoz Jiménez','2º ASIR');
INSERT INTO profesores VALUES(47,'Lourdes','Navas Malagón','-');
INSERT INTO profesores VALUES(48,'Antonio José','Negro Lozano','-');
INSERT INTO profesores VALUES(49,'Rocío','Ojeda Rodríguez','3º ESO B');
INSERT INTO profesores VALUES(50,'Francisco','Palomares Merino','-');
INSERT INTO profesores VALUES(51,'Rosario','Pazo Sarria','1º ESO B');
INSERT INTO profesores VALUES(52,'María del Carmen','Pedraza Mejías','2º APSD');
INSERT INTO profesores VALUES(53,'Rafael','Peña Herrador','2º SMR');
INSERT INTO profesores VALUES(54,'María José','Piña Rojas','-');
INSERT INTO profesores VALUES(55,'María Isabel','Ponferrada Marín','-');
INSERT INTO profesores VALUES(56,'Virginia','Porcuna Castillo','-');
INSERT INTO profesores VALUES(57,'María del Carmen','Porras Macías','-');
INSERT INTO profesores VALUES(58,'Manuel','Quesada Pegalajar','-');
INSERT INTO profesores VALUES(59,'María del Pilar','Ramírez Boo','4º ESO B');
INSERT INTO profesores VALUES(60,'Consuelo Virginia','Ramos Pérez','2º ESO A');
INSERT INTO profesores VALUES(61,'María del Pilar','Reguera Vázquez','2º ESO B');
INSERT INTO profesores VALUES(62,'Pedro Jesús','Reina Carmona','-');
INSERT INTO profesores VALUES(63,'Francisco José','Requena Miranda','1º ESO A');
INSERT INTO profesores VALUES(64,'Natalia','Rivera Herrera','1º AFI');
INSERT INTO profesores VALUES(65,'Sergio Fernando','Rodríguez García','4º ESO A');
INSERT INTO profesores VALUES(66,'Luis Manuel','Romero Galán','-');
INSERT INTO profesores VALUES(67,'Alicia Lourdes','Ruiz Bello','1º APSD');
INSERT INTO profesores VALUES(68,'Juan Carlos','Sánchez Casares','1º FPB');
INSERT INTO profesores VALUES(69,'Encarnación','Sánchez Jiménez','-');
INSERT INTO profesores VALUES(70,'María Asunción','Sánchez Rodríguez','1º CGA B');
INSERT INTO profesores VALUES(71,'María Dolores','Sarabia Castro','3º ESO A');
INSERT INTO profesores VALUES(72,'José Manuel','Toledo Martínez','-');
INSERT INTO profesores VALUES(73,'Marcos','Tovar Urbina','-');
INSERT INTO profesores VALUES(74,'María Luisa','Vaquero Aguilar','1º ESO D');
INSERT INTO profesores VALUES(75,'Antonio Ramón','Vázquez León','1º SMR');
INSERT INTO profesores VALUES(76,'José Enrique','Viola Nevado','-');
